<?php

namespace Database\Seeders;

use App\Models\EducationContent;
use App\Models\User;
use Illuminate\Database\Seeder;

class EducationContentSeeder extends Seeder
{
    public function run(): void
    {
        $author = User::first() ?? User::factory()->create([
            'name' => 'Admin Harmoni',
            'email' => 'admin@harmoni.test',
        ]);

        $contents = [

            // ========================================================================
            // ISLAM (religion_id = 1)
            // ========================================================================
            ['religion_id' => 1, 'author_id' => $author->id, 'title' => 'Rukun Islam: Pilar Utama Kehidupan Seorang Muslim', 'slug' => 'rukun-islam-pilar-utama', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Semua Umur', 'views_count' => 245, 'content' => 'Rukun Islam adalah lima pilar utama yang menjadi fondasi kehidupan setiap Muslim. Kelima pilar ini bukan sekadar ritual, melainkan panduan hidup yang membentuk karakter dan hubungan seorang hamba dengan Allah SWT serta sesama manusia.'."\n\n".'1. Syahadat (Persaksian)'."\n".'Mengucapkan dua kalimat syahadat dengan penuh keyakinan. Ini adalah pintu masuk ke dalam Islam dan pengakuan bahwa hanya Allah yang berhak disembah.'."\n\n".'2. Shalat'."\n".'Melaksanakan shalat lima waktu sehari semalam. Shalat adalah tiang agama dan komunikasi langsung antara hamba dengan Tuhannya.'."\n\n".'3. Puasa Ramadhan'."\n".'Menahan diri dari makan, minum, dan hawa nafsu dari terbit fajar hingga terbenam matahari selama bulan Ramadhan.'."\n\n".'4. Zakat'."\n".'Mengeluarkan sebagian harta untuk diberikan kepada yang berhak menerimanya. Zakat membersihkan harta dan jiwa.'."\n\n".'5. Haji'."\n".'Melaksanakan ibadah haji ke Baitullah bagi yang mampu secara fisik, finansial, dan aman perjalanannya.'],
            ['religion_id' => 1, 'author_id' => $author->id, 'title' => 'Tata Cara Wudhu yang Benar Sesuai Sunnah', 'slug' => 'tata-cara-wudhu-sesuai-sunnah', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Semua Umur', 'views_count' => 189, 'content' => 'Wudhu adalah syarat sah shalat dan sekaligus ibadah yang memiliki nilai pahala tersendiri. Tata cara wudhu yang benar: niat, basuh telapak tangan, kumur-kumur, bersihkan hidung, basuh muka, basuh tangan hingga siku, usap kepala dan telinga, basuh kaki hingga mata kaki, tertib dan tidak terputus. Sunah wudhu: bersiwak, mendahulukan kanan, mengulang 3 kali, tidak berlebihan air. Hal yang membatalkan wudhu: keluar sesuatu dari kemaluan/dubur, hilang akal, menyentuh kemaluan.'],
            ['religion_id' => 1, 'author_id' => $author->id, 'title' => 'Keutamaan Membaca Al-Quran di Bulan Ramadhan', 'slug' => 'keutamaan-membaca-alquran-ramadhan', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Semua Umur', 'views_count' => 312, 'content' => 'Bulan Ramadhan adalah bulan yang istimewa karena Al-Quran pertama kali diturunkan pada bulan yang penuh berkah ini. Keutamaan membaca Al-Quran di bulan Ramadhan: pahala berlipat ganda, syafaat di hari kiamat, ketenangan hati, meningkatkan takwa. Tips mengkhatamkan Al-Quran: baca 1 juz per hari, bagi waktu setelah setiap shalat wajib, gunakan aplikasi digital, bergabung kelompok tadarus.'],
            ['religion_id' => 1, 'author_id' => $author->id, 'title' => 'Doa Harian yang Dianjurkan untuk Anak Muslim', 'slug' => 'doa-harian-anak-muslim', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Anak-anak', 'views_count' => 156, 'content' => 'Mengajarkan doa sehari-hari kepada anak sejak dini adalah investasi iman. Doa sebelum tidur, bangun tidur, sebelum makan, sesudah makan, masuk kamar mandi. Ajarkan dengan cara bernyanyi agar mudah diingat, biasakan membaca doa bersama, beri contoh langsung, gunakan buku bergambar.'],
            ['religion_id' => 1, 'author_id' => $author->id, 'title' => 'Sejarah Masjidil Haram', 'slug' => 'sejarah-masjidil-haram', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Remaja & Dewasa', 'views_count' => 98, 'content' => 'Masjidil Haram dibangun pertama kali oleh Nabi Ibrahim AS bersama putranya Nabi Ismail AS. Sebelum Islam, Ka\'bah menjadi pusat penyembahan berhala. Pada Fathu Makkah, Rasulullah membersihkan Ka\'bah. Perluasan terus dilakukan hingga mampu menampung 2 juta jamaah. Fakta menarik: pintu Ka\'bah dari emas 280 kg, Hajar Aswad dari surga, Maqam Ibrahim bekas pijakan Nabi Ibrahim.'],
            ['religion_id' => 1, 'author_id' => $author->id, 'title' => 'Keindahan Shalat Subuh', 'slug' => 'video-keindahan-shalat-subuh', 'content_type' => 'video', 'status' => 'approved', 'youtube_video_id' => 'dQw4w9WgXcQ', 'age_group' => 'Semua Umur', 'views_count' => 567, 'content' => 'Video tentang keutamaan shalat Subuh dan keberkahan pagi hari dalam Islam.'],
            ['religion_id' => 1, 'author_id' => $author->id, 'title' => 'Indahnya Masjid Nabawi', 'slug' => 'video-masjid-nabawi-virtual', 'content_type' => 'video', 'status' => 'approved', 'youtube_video_id' => 'dQw4w9WgXcQ', 'age_group' => 'Semua Umur', 'views_count' => 432, 'content' => 'Jelajahi keindahan Masjid Nabawi di Madinah.'],
            ['religion_id' => 1, 'author_id' => $author->id, 'title' => 'Belajar Tajwid: Hukum Nun Mati', 'slug' => 'video-belajar-tajwid-nun-mati', 'content_type' => 'video', 'status' => 'approved', 'youtube_video_id' => 'dQw4w9WgXcQ', 'age_group' => 'Remaja & Dewasa', 'views_count' => 723, 'content' => 'Pembelajaran tajwid dasar tentang hukum nun mati dan tanwin.'],

            // ========================================================================
            // KRISTEN (religion_id = 2)
            // ========================================================================
            ['religion_id' => 2, 'author_id' => $author->id, 'title' => 'Sejarah Alkitab: Perjanjian Lama dan Baru', 'slug' => 'sejarah-alkitab-perjanjian', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Semua Umur', 'views_count' => 187, 'content' => 'Alkitab adalah kitab suci umat Kristen yang terdiri dari Perjanjian Lama (39 kitab) dan Perjanjian Baru (27 kitab). Perjanjian Lama menceritakan penciptaan, hukum Taurat, dan nabi-nabi. Perjanjian Baru menceritakan kelahiran, pelayanan, kematian, dan kebangkitan Yesus Kristus serta awal mula gereja. Alkitab ditulis oleh sekitar 40 penulis dalam kurun waktu 1.500 tahun.'],
            ['religion_id' => 2, 'author_id' => $author->id, 'title' => 'Makna Natal bagi Umat Kristen', 'slug' => 'makna-natal-kristen', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Semua Umur', 'views_count' => 234, 'content' => 'Natal adalah perayaan kelahiran Yesus Kristus, Juruselamat dunia. Makna Natal: kasih Allah yang nyata dalam Yesus, pengharapan bagi dunia, damai sejahtera, dan sukacita. Tradisi Natal: ibadah malam Natal, pohon Natal, pertukaran kado, dan pelayanan kepada sesama. Natal mengingatkan kita untuk saling mengasihi seperti Kristus telah mengasihi kita.'],
            ['religion_id' => 2, 'author_id' => $author->id, 'title' => '10 Perintah Allah dalam Ajaran Kristen', 'slug' => 'sepuluh-perintah-allah', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Remaja & Dewasa', 'views_count' => 145, 'content' => 'Sepuluh Perintah Allah diberikan kepada Musa di Gunung Sinai. Perintah-perintah ini menjadi dasar moral dan etika dalam ajaran Kristen. Mulai dari mengasihi Tuhan, menghormati orang tua, tidak membunuh, tidak berzinah, tidak mencuri, hingga tidak mengingini milik sesama. Yesus menggenapi hukum ini dengan dua perintah utama: kasihi Tuhan dan kasihi sesama.'],
            ['religion_id' => 2, 'author_id' => $author->id, 'title' => 'Ibadah dan Pujian di Gereja', 'slug' => 'video-ibadah-pujian-gereja', 'content_type' => 'video', 'status' => 'approved', 'youtube_video_id' => 'dQw4w9WgXcQ', 'age_group' => 'Semua Umur', 'views_count' => 345, 'content' => 'Video tentang ibadah minggu di gereja dengan pujian penyembahan dan firman Tuhan.'],
            ['religion_id' => 2, 'author_id' => $author->id, 'title' => 'Doa Bapa Kami: Panduan Berdoa', 'slug' => 'video-doa-bapa-kami', 'content_type' => 'video', 'status' => 'approved', 'youtube_video_id' => 'dQw4w9WgXcQ', 'age_group' => 'Semua Umur', 'views_count' => 289, 'content' => 'Renungan tentang Doa Bapa Kami yang diajarkan Yesus kepada murid-murid-Nya.'],

            // ========================================================================
            // KATOLIK (religion_id = 3)
            // ========================================================================
            ['religion_id' => 3, 'author_id' => $author->id, 'title' => 'Tujuh Sakramen dalam Gereja Katolik', 'slug' => 'tujuh-sakramen-katolik', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Remaja & Dewasa', 'views_count' => 201, 'content' => 'Gereja Katolik memiliki tujuh sakramen: Baptis (pintu masuk gereja), Krisma (penguatan iman), Ekaristi (tubuh Kristus), Tobat (pengakuan dosa), Minyak Suci (pengurapan orang sakit), Imamat (tahbisan), dan Perkawinan (ikatan suci). Setiap sakramen adalah tanda rahmat Allah yang kudus dan dipercayakan kepada Gereja.'],
            ['religion_id' => 3, 'author_id' => $author->id, 'title' => 'Sejarah Gereja Katolik di Indonesia', 'slug' => 'sejarah-gereja-katolik-indonesia', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Semua Umur', 'views_count' => 167, 'content' => 'Gereja Katolik masuk ke Indonesia melalui para misionaris Portugis pada abad ke-16. Fransiskus Xaverius menyebarkan agama Katolik di Maluku dan sekitarnya. Kini Gereja Katolik Indonesia terbagi dalam 37 keuskupan dengan jumlah umat sekitar 8 juta jiwa. Kontribusi Gereja Katolik dalam pendidikan dan kesehatan sangat signifikan.'],
            ['religion_id' => 3, 'author_id' => $author->id, 'title' => 'Misa Kudus: Makna dan Liturgi', 'slug' => 'makna-misa-kudus', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Semua Umur', 'views_count' => 178, 'content' => 'Misa Kudus adalah puncak ibadah Gereja Katolik. Terdiri dari Ritus Pembuka (tanda salib, pengakuan dosa), Liturgi Sabda (bacaan Alkitab, khotbah), Liturgi Ekaristi (persembahan, konsekrasi, komuni), dan Ritus Penutup (berkat). Umat Katolik wajib mengikuti misa setiap hari Minggu dan hari raya.'],
            ['religion_id' => 3, 'author_id' => $author->id, 'title' => 'Doa Rosario Bersama', 'slug' => 'video-doa-rosario', 'content_type' => 'video', 'status' => 'approved', 'youtube_video_id' => 'dQw4w9WgXcQ', 'age_group' => 'Semua Umur', 'views_count' => 312, 'content' => 'Video doa Rosario lengkap dengan misteri-misteri iman Katolik.'],
            ['religion_id' => 3, 'author_id' => $author->id, 'title' => 'Perayaan Ekaristi Mingguan', 'slug' => 'video-perayaan-ekaristi', 'content_type' => 'video', 'status' => 'approved', 'youtube_video_id' => 'dQw4w9WgXcQ', 'age_group' => 'Semua Umur', 'views_count' => 256, 'content' => 'Ibadah misa kudus hari Minggu dari Gereja Katolik.'],

            // ========================================================================
            // HINDU (religion_id = 4)
            // ========================================================================
            ['religion_id' => 4, 'author_id' => $author->id, 'title' => 'Sejarah Agama Hindu di Bali', 'slug' => 'sejarah-hindu-bali', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Semua Umur', 'views_count' => 192, 'content' => 'Agama Hindu masuk ke Indonesia pada abad pertama Masehi melalui pedagang India. Hindu berkembang pesat di Kerajaan Majapahit dan Mataram Kuno. Setelah runtuhnya Majapahit, Hindu bertahan di Bali. Kini Bali menjadi pusat Hindu Indonesia dengan tradisi unik yang memadukan ajaran Hindu dengan budaya lokal.'],
            ['religion_id' => 4, 'author_id' => $author->id, 'title' => 'Makna Hari Raya Nyepi', 'slug' => 'makna-hari-raya-nyepi', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Semua Umur', 'views_count' => 215, 'content' => 'Nyepi adalah Tahun Baru Saka yang dirayakan dengan diam total. Catur Bratha Penyepian: amati geni (tiada api), amati karya (tiada kerja), amati lelungan (tiada bepergian), amati lelanguan (tiada hiburan). Rangkaian Nyepi: Melasti (pembersihan), Tawur Agung (pecaruan), Nyepi (diam), Ngembak Geni (bersilaturahmi).'],
            ['religion_id' => 4, 'author_id' => $author->id, 'title' => 'Weda: Kitab Suci Agama Hindu', 'slug' => 'wedah-kitab-suci-hindu', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Remaja & Dewasa', 'views_count' => 134, 'content' => 'Weda adalah kitab suci agama Hindu yang terdiri dari empat bagian: Reg Weda (pujian), Yajur Weda (doa), Sama Weda (lagu), dan Atharwa Weda (mantra). Weda berisi ajaran tentang kebenaran tertinggi, dharma, karma, dan moksha. Weda diyakini sebagai wahyu dari Hyang Widhi Wasa.'],
            ['religion_id' => 4, 'author_id' => $author->id, 'title' => 'Tari Kecak: Seni dan Spiritualitas', 'slug' => 'video-tari-kecak', 'content_type' => 'video', 'status' => 'approved', 'youtube_video_id' => 'dQw4w9WgXcQ', 'age_group' => 'Semua Umur', 'views_count' => 456, 'content' => 'Video pertunjukan Tari Kecak yang mengisahkan Ramayana dengan latar Pura Uluwatu.'],
            ['religion_id' => 4, 'author_id' => $author->id, 'title' => 'Upacara Melasti di Pantai', 'slug' => 'video-upacara-melasti', 'content_type' => 'video', 'status' => 'approved', 'youtube_video_id' => 'dQw4w9WgXcQ', 'age_group' => 'Semua Umur', 'views_count' => 321, 'content' => 'Dokumentasi upacara Melasti menyambut Nyepi di Bali.'],

            // ========================================================================
            // BUDDHA (religion_id = 5)
            // ========================================================================
            ['religion_id' => 5, 'author_id' => $author->id, 'title' => 'Riwayat Siddharta Gautama', 'slug' => 'riwayat-siddharta-gautama', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Semua Umur', 'views_count' => 223, 'content' => 'Siddharta Gautama lahir sebagai pangeran di Kapilavastu. Ia meninggalkan kehidupan istana untuk mencari kebenaran. Setelah bertapa selama 6 tahun, ia mencapai pencerahan di Bodhgaya. Ia kemudian mengajarkan Jalan Tengah, Empat Kebenaran Mulia, dan Jalan Berunsur Delapan. Ajaran Buddha menyebar luas di Asia.'],
            ['religion_id' => 5, 'author_id' => $author->id, 'title' => 'Candi Borobudur: Warisan Buddha Dunia', 'slug' => 'candi-borobudur-warisan-buddha', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Semua Umur', 'views_count' => 278, 'content' => 'Candi Borobudur adalah candi Buddha terbesar di dunia yang dibangun oleh Dinasti Syailendra pada abad ke-9. Terdiri dari 10 tingkatan yang melambangkan perjalanan menuju pencerahan. Relief-reliefnya menceritakan ajaran Buddha. Borobudur menjadi pusat perayaan Waisak nasional setiap tahun.'],
            ['religion_id' => 5, 'author_id' => $author->id, 'title' => 'Meditasi Vipassana untuk Pemula', 'slug' => 'meditasi-vipassana-pemula', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Remaja & Dewasa', 'views_count' => 156, 'content' => 'Meditasi Vipassana adalah teknik meditasi untuk melihat realitas sebagaimana adanya. Fokus pada napas dan sensasi tubuh. Manfaat: menenangkan pikiran, mengurangi stres, meningkatkan kesadaran. Langkah awal: duduk nyaman, tutup mata, fokus pada napas masuk-keluar, amati pikiran tanpa terikat.'],
            ['religion_id' => 5, 'author_id' => $author->id, 'title' => 'Perayaan Waisak di Borobudur', 'slug' => 'video-waisak-borobudur', 'content_type' => 'video', 'status' => 'approved', 'youtube_video_id' => 'dQw4w9WgXcQ', 'age_group' => 'Semua Umur', 'views_count' => 543, 'content' => 'Video perayaan Waisak di Candi Borobudur, puncak tahun Buddhist.'],
            ['religion_id' => 5, 'author_id' => $author->id, 'title' => 'Meditasi Kesadaran Penuh', 'slug' => 'video-meditasi-kesadaran', 'content_type' => 'video', 'status' => 'approved', 'youtube_video_id' => 'dQw4w9WgXcQ', 'age_group' => 'Semua Umur', 'views_count' => 401, 'content' => 'Panduan meditasi kesadaran penuh (mindfulness) dalam tradisi Buddha.'],

            // ========================================================================
            // KONGHUCU (religion_id = 6)
            // ========================================================================
            ['religion_id' => 6, 'author_id' => $author->id, 'title' => 'Ajaran Konfusius: Jalan Kebajikan', 'slug' => 'ajaran-konfusius-kebajikan', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Semua Umur', 'views_count' => 143, 'content' => 'Konfusius (Kong Hu Cu) adalah filsuf besar Tiongkok yang ajarannya menjadi fondasi agama Konghucu. Ajaran inti: Ren (kebajikan), Yi (kebenaran), Li (tata krama), Zhi (kebijaksanaan), Xin (kepercayaan). Kitab suci: Si Shu (Empat Kitab) dan Wu Jing (Lima Klasik). Nilai utama: bakti kepada orang tua (xiao) dan kesetiaan kepada negara.'],
            ['religion_id' => 6, 'author_id' => $author->id, 'title' => 'Tradisi Tahun Baru Imlek', 'slug' => 'tradisi-tahun-baru-imlek', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Semua Umur', 'views_count' => 198, 'content' => 'Tahun Baru Imlek adalah hari raya terpenting bagi umat Konghucu. Tradisi: bersih-bersih rumah, sembahyang leluhur, makan malam bersama, angpao, barongsai, dan lampion. Imlek melambangkan permulaan baru dan harapan. Perayaan berlangsung 15 hari, diakhiri dengan Cap Go Meh.'],
            ['religion_id' => 6, 'author_id' => $author->id, 'title' => 'Makna Klenteng dan Altar Sembahyang', 'slug' => 'makna-klenteng-altar-sembahyang', 'content_type' => 'article', 'status' => 'approved', 'age_group' => 'Remaja & Dewasa', 'views_count' => 112, 'content' => 'Klenteng adalah tempat ibadah umat Konghucu. Altar utama untuk Tian (Tuhan). Altar tambahan untuk leluhur dan nabi. Perlengkapan: hio (dupa), lilin, meja altar. Tata cara sembahyang: membakar hio, berdoa dengan sikap tangan terlipat, membungkuk. Warna merah melambangkan keberuntungan.'],
            ['religion_id' => 6, 'author_id' => $author->id, 'title' => 'Perayaan Cap Go Meh', 'slug' => 'video-cap-go-meh', 'content_type' => 'video', 'status' => 'approved', 'youtube_video_id' => 'dQw4w9WgXcQ', 'age_group' => 'Semua Umur', 'views_count' => 234, 'content' => 'Video perayaan Cap Go Meh, puncak Tahun Baru Imlek.'],
            ['religion_id' => 6, 'author_id' => $author->id, 'title' => 'Ritual Sembahyang Leluhur', 'slug' => 'video-sembahyang-leluhur', 'content_type' => 'video', 'status' => 'approved', 'youtube_video_id' => 'dQw4w9WgXcQ', 'age_group' => 'Semua Umur', 'views_count' => 167, 'content' => 'Video tentang tradisi sembahyang leluhur dalam ajaran Konghucu.'],
        ];

        foreach ($contents as $content) {
            EducationContent::updateOrCreate(['slug' => $content['slug']], $content);
        }

        $total = count($contents);
        $this->command->info("Seeded {$total} education contents for all 6 religions.");
    }
}
